.PHONY: dev build db-migrate db-generate db-studio db-up db-down

run:
	npm run dev

build:
	npm run build

db-migrate:
	npm run db:migrate

db-generate:
	npm run db:generate

db-studio:
	npm run db:studio

db-up:
	./scripts/dev-db.sh up

db-down:
	./scripts/dev-db.sh down
